[profile.default]
src = 'src'
out = 'out'
test = 'tests'
script = 'scripts'
cache_path = 'cache'
libs = ['node_modules', 'lib']
ffi = true
evm_version = 'paris'
solc_version = '0.8.22'
bytecode_hash = 'none'
extra_output_files = ['metadata']
ignored_warnings_from = [
    'src/contracts/facilitators/aave/tokens/GhoAToken.sol',
    'src/contracts/facilitators/aave/interestStrategy/ZeroDiscountRateStrategy.sol',
    'lib/aave-v3-origin/src/contracts/treasury/RevenueSplitter.sol',
    'lib/aave-v3-origin/src/contracts/dependencies/openzeppelin/ReentrancyGuard.sol',
    'lib/aave-v3-origin/src/contracts/protocol/tokenization/base/IncentivizedERC20.sol',
]
optimizer = true
optimizer_runs = 200

