name: certora-steward

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      statuses: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Munged
        run: |
          cd certora/steward
          touch applyHarness.patch
          make munged

      - uses: Certora/certora-run-action@v2
        with:
          cli-version: 7.31.2
          configurations: |-
            certora/steward/conf/GhoAaveSteward.conf
            certora/steward/conf/GhoBucketSteward.conf
            certora/steward/conf/GhoCcipSteward.conf
            certora/steward/conf/GhoGsmSteward.conf
          solc-versions: 0.8.10
          comment-fail-only: false
          solc-remove-version-prefix: "0."
          job-name: "Certora Prover Run"
          certora-key: ${{ secrets.CERTORAKEY }}
          install-java: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
